/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function DeskTest(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("./glb/deskWood.glb");
    const deskTest = useGLTF('./glb/deskWood.glb')
    const animation = useAnimations(deskTest.animations, deskTest.scene)

    console.log(animation)

useEffect(() =>
    {
        const action = animation.actions.openDesk
        action.play()
    }, [])
    const openDesk = () => {
        animation.actions.openDesk.reset()
        animation.actions.openDesk.setLoop(1,1)
        animation.actions.openDesk.play()
    }

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="Sketchfab_model"
                    position={[0, 0.457, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.273}
                    onClick={() => openDesk()}
                >
                    <group name="Root">
                        <group name="Cube001">
                            <mesh
                                name="Cube_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube_0.geometry}
                                material={materials.Wood}
                                position={[0, 0, -0.016]}
                            />
                        </group>
                        <group name="Cube002" position={[-2.35, 0, -1.49]}>
                            <mesh
                                name="Cube002_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube002_0.geometry}
                                material={materials.Wood}
                            />
                        </group>
                        <group name="Cube003" position={[0, 0.8, -1.05]}>
                            <mesh
                                name="Cube003_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube003_0.geometry}
                                material={materials.Wood}
                            />
                        </group>
                        <group name="Cube004" position={[-1.525, -1.25, -0.2]}>
                            <mesh
                                name="Cube004_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube004_0.geometry}
                                material={materials.Wood}
                            />
                        </group>
                        <group name="Cube005" position={[2.35, 0, -1.49]}>
                            <mesh
                                name="Cube001_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube001_0.geometry}
                                material={materials.Wood}
                            />
                        </group>
                        <group name="Cube006" position={[1.525, -1.25, -0.2]}>
                            <mesh
                                name="Cube005_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube005_0.geometry}
                                material={materials.Wood}
                            />
                        </group>
                        <group name="Cube007" position={[0, -1.25, -0.2]}>
                            <mesh
                                name="drawer"
                                castShadow
                                receiveShadow
                                geometry={nodes.drawer.geometry}
                                material={materials.Wood}
                            />
                        </group>
                        <group name="Cube008" position={[-1.525, -0.29, -0.3]}>
                            <mesh
                                name="Cube007_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube007_0.geometry}
                                material={materials.Wood}
                            />
                        </group>
                        <group name="Cube009" position={[0, -0.29, -0.3]} />
                        <group name="Cube010" position={[1.525, -0.29, -0.3]}>
                            <mesh
                                name="Cube009_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube009_0.geometry}
                                material={materials.Wood}
                            />
                        </group>
                        <group name="Cube011" position={[-0.762, -0.213, -0.2]} />
                        <group name="Cube012" position={[0.762, -0.213, -0.2]} />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("./glb/deskWood.glb");
